root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./main ."
  bin = "./main"
  full_bin = "./main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "internal/db/migrations"]
  delay = 200
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true

[misc]
  clean_on_exit = false
